meta_product_name: Ходки
meta_title: Ходки - Походы около Москвы
meta_description: ""
meta_image: "cover.jpg"         # should exist in `app/assets/images/`
# twitter_account: ""   # required for Twitter Cards
